### ISSUE TITLE
Missing shared objects

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS-SCENERY/RJBB-fg-CustomScenery#1]
See the comment on commit
 https://github.com/FGMEMBERS-SCENERY/RJBB-fg-CustomScenery/commit/07ea765317a6563602455dffbef4b38556b37c39
Several objects need to be imported. 

I tried finding these without success.

Best,
@IAHM-COL

**Comment by legoboyvdlp** [comment]
Rogah, I'll fix it.

**Comment by FGDATA** [comment]
several had been fixed
New models need import now

See comment on commit:
https://github.com/FGMEMBERS-SCENERY/RJBB-fg-CustomScenery/commit/24eadd0d5721f877e58f7f37b784246c39b5294d

**Comment by FGDATA** [comment]
Currently Clean. Thanks
IH-COL

**Comment by legoboyvdlp** [comment]
Cheers
